/**
 * Cloudflare Worker for RAG Blog System
 * Proxies requests to Gemini API with secure API key
 */

export default {
  async fetch(request, env) {
    // ===== CORS Headers =====
    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type',
    };

    // Handle CORS preflight requests
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        status: 204,
        headers: corsHeaders
      });
    }

    // Only allow POST requests
    if (request.method !== 'POST') {
      return new Response(
        JSON.stringify({ error: 'Method not allowed. Use POST.' }),
        {
          status: 405,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json'
          }
        }
      );
    }

    try {
      // ===== Read request body =====
      const { question, context } = await request.json();

      // Validation
      if (!question || !context) {
        return new Response(
          JSON.stringify({
            error: 'Missing required fields: question and context'
          }),
          {
            status: 400,
            headers: {
              ...corsHeaders,
              'Content-Type': 'application/json'
            }
          }
        );
      }

      // Normalize context to string (accept both string and array)
      const contextText = Array.isArray(context) ? context.join('\n\n---\n\n') : context;

      // Logs for debugging
      console.log('Question received:', question.substring(0, 50) + '...');
      console.log('Context length:', contextText.length, 'characters');

      // ===== Build prompt for Gemini =====
      const prompt = `Tu es un assistant pédagogique expert en machine learning et en transformers.

CONTEXTE (extraits pertinents de l'article) :
${contextText}

QUESTION DU LECTEUR :
${question}

INSTRUCTIONS :
- Réponds en te basant UNIQUEMENT sur le contexte fourni ci-dessus
- Si l'information n'est pas dans le contexte, dis-le clairement
- Sois concis (3-5 phrases maximum)
- Utilise un ton pédagogique et accessible
- Si possible, cite ou reformule des passages du contexte

RÉPONSE :`;

      // ===== Call Gemini API =====
      // Use the latest compatible Gemini model
      const geminiModel = env.GEMINI_MODEL || 'gemini-2.0-flash-exp';
      const geminiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${geminiModel}:generateContent?key=${env.GEMINI_API_KEY}`;

      const geminiResponse = await fetch(geminiUrl, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [{
              text: prompt
            }]
          }],
          generationConfig: {
            temperature: 0.7,
            maxOutputTokens: 500,
            topP: 0.9,
            topK: 40,
          }
        })
      });

      // Check response
      if (!geminiResponse.ok) {
        const errorText = await geminiResponse.text();
        console.error('Gemini API error:', errorText);

        // More helpful message when the model is not available
        const modelHint = errorText.includes('NOT_FOUND')
          ? `Model "${geminiModel}" is not available for this API key/version. Try setting GEMINI_MODEL secret.`
          : null;

        return new Response(
          JSON.stringify({
            error: `Gemini API error: ${geminiResponse.status}`,
            details: errorText,
            hint: modelHint
          }),
          {
            status: 502,
            headers: {
              ...corsHeaders,
              'Content-Type': 'application/json'
            }
          }
        );
      }

      const geminiData = await geminiResponse.json();

      // ===== Extract answer =====
      const answer = geminiData.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!answer) {
        console.error('No answer in Gemini response:', geminiData);
        return new Response(
          JSON.stringify({
            error: 'No answer generated by Gemini',
            rawResponse: geminiData
          }),
          {
            status: 500,
            headers: {
              ...corsHeaders,
              'Content-Type': 'application/json'
            }
          }
        );
      }

      // ===== Return response =====
      return new Response(
        JSON.stringify({
          answer: answer,
          tokensUsed: geminiData.usageMetadata?.totalTokenCount || 'unknown'
        }),
        {
          status: 200,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json',
          }
        }
      );

    } catch (error) {
      // Handle errors
      console.error('Worker error:', error);

      return new Response(
        JSON.stringify({
          error: 'Internal server error',
          message: error.message
        }),
        {
          status: 500,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json',
          }
        }
      );
    }
  }
};
